/**
 * Premium palette definitions: curated, battle-tested color schemes from the
 * editor/design-tool ecosystem (Tokyo Night, Nord, Catppuccin, Everforest,
 * Rosé Pine, Ayu Mirage), registered through the theme runtime's third-party
 * extension point as theme definitions whose alias-token maps paint the whole
 * UI — backgrounds, borders, brand, text, code surfaces, sidebar, scrollbars
 * — not just a tinted base.
 *
 * Every palette rides the standard theme runtime: `colorScheme` selects the
 * base palette the presenter projects onto `body[data-ds-dark-theme]`, and
 * `tokens` override `--dsw-alias-*` / `--dsw-specific-*` variables inline.
 * Unlisted tokens fall back to the base light/dark palette.
 */
import type { PremiumThemesKey } from './client/locales.ts'
import type { PALETTE_PREFERENCES } from './theme-settings.ts'

/** Preference id union of the premium palettes. */
export type PalettePreference = typeof PALETTE_PREFERENCES[number]

/** One selectable premium palette. */
export interface PremiumPalette {
  /** Palette id (persisted through the plugin's settings section). */
  id: PalettePreference
  /** Base palette this scheme builds on. */
  colorScheme: 'light' | 'dark'
  /** Palette-row copy key (`settings.premiumThemes` namespace). */
  labelKey: PremiumThemesKey
  /** Signature accent for the settings swatch. */
  swatchAccent: string
  /** Signature background for the settings swatch. */
  swatchBackground: string
  /** Alias/specific token overrides applied over the base palette. */
  tokens: Record<string, string>
}

export const PREMIUM_PALETTES: readonly PremiumPalette[] = [
  {
    id: 'tokyo-night',
    colorScheme: 'dark',
    labelKey: 'palette.tokyoNight',
    swatchAccent: '#7aa2f7',
    swatchBackground: '#16161e',
    tokens: {
      '--dsw-alias-bg-base': '#16161e',
      '--dsw-alias-bg-layer-1': '#16161e',
      '--dsw-alias-bg-layer-2': '#1a1b26',
      '--dsw-alias-bg-layer-3': '#1f2335',
      '--dsw-alias-bg-overlay': '#292e42',
      '--dsw-alias-bg-module-platform': '#1f2335',
      '--dsw-alias-bg-multi-select': '#1a1b26',
      '--dsw-alias-bg-skeleton': 'rgba(192, 202, 245, 0.08)',
      '--dsw-alias-bg-mask-drop': 'rgba(22, 22, 30, 0.72)',
      '--dsw-alias-border-l1': 'rgba(122, 162, 247, 0.1)',
      '--dsw-alias-border-l2': 'rgba(122, 162, 247, 0.16)',
      '--dsw-alias-border-l2-darkmode-thin': 'rgba(122, 162, 247, 0.1)',
      '--dsw-alias-border-l3': 'rgba(122, 162, 247, 0.24)',
      '--dsw-alias-border-l4': 'rgba(122, 162, 247, 0.32)',
      '--dsw-alias-border-inverted': 'rgba(0, 0, 0, 0.2)',
      '--dsw-alias-border-inverted2': 'rgba(0, 0, 0, 0.34)',
      '--dsw-alias-brand-primary': '#7aa2f7',
      '--dsw-alias-brand-primary-invert': '#16161e',
      '--dsw-alias-brand-primary-new-colorprimary-new-color': '#7aa2f7',
      '--dsw-alias-brand-text': '#c0caf5',
      '--dsw-alias-button-primary-fill': '#7aa2f7',
      '--dsw-alias-button-primary-hover': '#89b1ff',
      '--dsw-alias-button-primary-dimmed': '#1f2335',
      '--dsw-alias-button-info-fill': '#7aa2f7',
      '--dsw-alias-button-info-hover': '#89b1ff',
      '--dsw-alias-button-contrast-fill': '#c0caf5',
      '--dsw-alias-button-elevated-fill': '#1f2335',
      '--dsw-alias-button-floating-fill': '#292e42',
      '--dsw-alias-button-floating-hover': '#343b58',
      '--dsw-alias-button-ghost-active-border': '#565f89',
      '--dsw-alias-button-ghost-active-fill': '#1f2335',
      '--dsw-alias-button-ghost-active-hover': '#292e42',
      '--dsw-alias-interactive-bg-hover': 'rgba(122, 162, 247, 0.1)',
      '--dsw-alias-interactive-bg-active': 'rgba(122, 162, 247, 0.16)',
      '--dsw-alias-interactive-bg-hover-accent': 'rgba(187, 154, 247, 0.18)',
      '--dsw-alias-interactive-bg-hover-solid': '#292e42',
      '--dsw-alias-interactive-bg-hover-danger': 'rgba(247, 118, 142, 0.15)',
      '--dsw-alias-label-primary': '#c0caf5',
      '--dsw-alias-label-secondary': '#a9b1d6',
      '--dsw-alias-label-tertiary': '#565f89',
      '--dsw-alias-label-caption': '#565f89',
      '--dsw-alias-label-dimmed': '#343b58',
      '--dsw-alias-label-primary-foreground': '#16161e',
      '--dsw-alias-label-primary-inverted': '#16161e',
      '--dsw-alias-label-primary-bluish': '#c0caf5',
      '--dsw-alias-label-primary-dimmed': '#343b58',
      '--dsw-alias-markdown-code-block': '#1a1b26',
      '--dsw-alias-markdown-code-block-banner': '#1f2335',
      '--dsw-alias-markdown-inline-code': '#1f2335',
      '--dsw-alias-markdown-citation': '#292e42',
      '--dsw-alias-markdown-tag': '#1f2335',
      '--dsw-alias-markdown-placeholder': '#1f2335',
      '--dsw-alias-markdown-code-segment-selected': '#1f2335',
      '--dsw-alias-markdown-code-segment-unselected': '#16161e',
      '--dsw-alias-scrollbar-bg-l1': '#292e42',
      '--dsw-alias-scrollbar-bg-l2': '#343b58',
      '--dsw-alias-scrollbar-hover-l1': '#343b58',
      '--dsw-alias-scrollbar-hover-l2': '#414868',
      '--dsw-alias-state-business-primary': '#7aa2f7',
      '--dsw-alias-state-business-tertiary': '#1f2335',
      '--dsw-alias-toast-bg': '#343b58',
      '--dsw-alias-tooltip-bg': '#343b58',
      '--dsw-specific-bubble': '#1a1b26',
      '--dsw-specific-bubble-highlight': '#1f2335',
      '--dsw-specific-input-major': '#1a1b26',
      '--dsw-specific-login-input': '#16161e',
      '--dsw-specific-selector': '#1f2335',
      '--dsw-specific-sidebar-fill': '#16161e',
      '--dsw-specific-sidebar-nav-item-active': '#1f2335',
      '--dsw-specific-sidebar-nav-item-active-accent': '#292e42',
      '--dsw-specific-sidebar-nav-item-hover': '#1a1b26',
      '--dsw-specific-tip': '#1f2335',
    },
  },
  {
    id: 'nord',
    colorScheme: 'dark',
    labelKey: 'palette.nord',
    swatchAccent: '#88c0d0',
    swatchBackground: '#2e3440',
    tokens: {
      '--dsw-alias-bg-base': '#2e3440',
      '--dsw-alias-bg-layer-1': '#2e3440',
      '--dsw-alias-bg-layer-2': '#3b4252',
      '--dsw-alias-bg-layer-3': '#434c5e',
      '--dsw-alias-bg-overlay': '#4c566a',
      '--dsw-alias-bg-module-platform': '#3b4252',
      '--dsw-alias-bg-multi-select': '#2e3440',
      '--dsw-alias-bg-skeleton': 'rgba(236, 239, 244, 0.08)',
      '--dsw-alias-bg-mask-drop': 'rgba(46, 52, 64, 0.72)',
      '--dsw-alias-border-l1': 'rgba(236, 239, 244, 0.08)',
      '--dsw-alias-border-l2': 'rgba(236, 239, 244, 0.14)',
      '--dsw-alias-border-l2-darkmode-thin': 'rgba(236, 239, 244, 0.08)',
      '--dsw-alias-border-l3': 'rgba(236, 239, 244, 0.2)',
      '--dsw-alias-border-l4': 'rgba(236, 239, 244, 0.28)',
      '--dsw-alias-border-inverted': 'rgba(0, 0, 0, 0.2)',
      '--dsw-alias-border-inverted2': 'rgba(0, 0, 0, 0.34)',
      '--dsw-alias-brand-primary': '#88c0d0',
      '--dsw-alias-brand-primary-invert': '#2e3440',
      '--dsw-alias-brand-primary-new-colorprimary-new-color': '#88c0d0',
      '--dsw-alias-brand-text': '#eceff4',
      '--dsw-alias-button-primary-fill': '#88c0d0',
      '--dsw-alias-button-primary-hover': '#9ed1dd',
      '--dsw-alias-button-primary-dimmed': '#3b4252',
      '--dsw-alias-button-info-fill': '#5e81ac',
      '--dsw-alias-button-info-hover': '#7093bd',
      '--dsw-alias-button-contrast-fill': '#eceff4',
      '--dsw-alias-button-elevated-fill': '#3b4252',
      '--dsw-alias-button-floating-fill': '#434c5e',
      '--dsw-alias-button-floating-hover': '#4c566a',
      '--dsw-alias-button-ghost-active-border': '#7b88a1',
      '--dsw-alias-button-ghost-active-fill': '#3b4252',
      '--dsw-alias-button-ghost-active-hover': '#434c5e',
      '--dsw-alias-interactive-bg-hover': 'rgba(236, 239, 244, 0.07)',
      '--dsw-alias-interactive-bg-active': 'rgba(236, 239, 244, 0.12)',
      '--dsw-alias-interactive-bg-hover-accent': 'rgba(136, 192, 208, 0.16)',
      '--dsw-alias-interactive-bg-hover-solid': '#434c5e',
      '--dsw-alias-interactive-bg-hover-danger': 'rgba(191, 97, 106, 0.15)',
      '--dsw-alias-label-primary': '#eceff4',
      '--dsw-alias-label-secondary': '#d8dee9',
      '--dsw-alias-label-tertiary': '#7b88a1',
      '--dsw-alias-label-caption': '#7b88a1',
      '--dsw-alias-label-dimmed': '#4c566a',
      '--dsw-alias-label-primary-foreground': '#2e3440',
      '--dsw-alias-label-primary-inverted': '#2e3440',
      '--dsw-alias-label-primary-bluish': '#eceff4',
      '--dsw-alias-label-primary-dimmed': '#4c566a',
      '--dsw-alias-markdown-code-block': '#3b4252',
      '--dsw-alias-markdown-code-block-banner': '#3b4252',
      '--dsw-alias-markdown-inline-code': '#3b4252',
      '--dsw-alias-markdown-citation': '#434c5e',
      '--dsw-alias-markdown-tag': '#3b4252',
      '--dsw-alias-markdown-placeholder': '#434c5e',
      '--dsw-alias-markdown-code-segment-selected': '#434c5e',
      '--dsw-alias-markdown-code-segment-unselected': '#2e3440',
      '--dsw-alias-scrollbar-bg-l1': '#434c5e',
      '--dsw-alias-scrollbar-bg-l2': '#4c566a',
      '--dsw-alias-scrollbar-hover-l1': '#4c566a',
      '--dsw-alias-scrollbar-hover-l2': '#5a6577',
      '--dsw-alias-state-business-primary': '#88c0d0',
      '--dsw-alias-state-business-tertiary': '#3b4252',
      '--dsw-alias-toast-bg': '#4c566a',
      '--dsw-alias-tooltip-bg': '#4c566a',
      '--dsw-specific-bubble': '#3b4252',
      '--dsw-specific-bubble-highlight': '#434c5e',
      '--dsw-specific-input-major': '#3b4252',
      '--dsw-specific-login-input': '#2e3440',
      '--dsw-specific-selector': '#3b4252',
      '--dsw-specific-sidebar-fill': '#2b313c',
      '--dsw-specific-sidebar-nav-item-active': '#3b4252',
      '--dsw-specific-sidebar-nav-item-active-accent': '#434c5e',
      '--dsw-specific-sidebar-nav-item-hover': '#333b48',
      '--dsw-specific-tip': '#3b4252',
    },
  },
  {
    id: 'catppuccin-mocha',
    colorScheme: 'dark',
    labelKey: 'palette.catppuccinMocha',
    swatchAccent: '#cba6f7',
    swatchBackground: '#1e1e2e',
    tokens: {
      '--dsw-alias-bg-base': '#1e1e2e',
      '--dsw-alias-bg-layer-1': '#1e1e2e',
      '--dsw-alias-bg-layer-2': '#181825',
      '--dsw-alias-bg-layer-3': '#313244',
      '--dsw-alias-bg-overlay': '#45475a',
      '--dsw-alias-bg-module-platform': '#313244',
      '--dsw-alias-bg-multi-select': '#181825',
      '--dsw-alias-bg-skeleton': 'rgba(205, 214, 244, 0.08)',
      '--dsw-alias-bg-mask-drop': 'rgba(30, 30, 46, 0.72)',
      '--dsw-alias-border-l1': 'rgba(205, 214, 244, 0.08)',
      '--dsw-alias-border-l2': 'rgba(205, 214, 244, 0.14)',
      '--dsw-alias-border-l2-darkmode-thin': 'rgba(205, 214, 244, 0.08)',
      '--dsw-alias-border-l3': 'rgba(205, 214, 244, 0.2)',
      '--dsw-alias-border-l4': 'rgba(205, 214, 244, 0.28)',
      '--dsw-alias-border-inverted': 'rgba(0, 0, 0, 0.2)',
      '--dsw-alias-border-inverted2': 'rgba(0, 0, 0, 0.34)',
      '--dsw-alias-brand-primary': '#cba6f7',
      '--dsw-alias-brand-primary-invert': '#1e1e2e',
      '--dsw-alias-brand-primary-new-colorprimary-new-color': '#cba6f7',
      '--dsw-alias-brand-text': '#cdd6f4',
      '--dsw-alias-button-primary-fill': '#cba6f7',
      '--dsw-alias-button-primary-hover': '#d7bdfa',
      '--dsw-alias-button-primary-dimmed': '#313244',
      '--dsw-alias-button-info-fill': '#89b4fa',
      '--dsw-alias-button-info-hover': '#9dc0fb',
      '--dsw-alias-button-contrast-fill': '#cdd6f4',
      '--dsw-alias-button-elevated-fill': '#313244',
      '--dsw-alias-button-floating-fill': '#45475a',
      '--dsw-alias-button-floating-hover': '#585b70',
      '--dsw-alias-button-ghost-active-border': '#6c7086',
      '--dsw-alias-button-ghost-active-fill': '#313244',
      '--dsw-alias-button-ghost-active-hover': '#45475a',
      '--dsw-alias-interactive-bg-hover': 'rgba(205, 214, 244, 0.07)',
      '--dsw-alias-interactive-bg-active': 'rgba(205, 214, 244, 0.12)',
      '--dsw-alias-interactive-bg-hover-accent': 'rgba(203, 166, 247, 0.16)',
      '--dsw-alias-interactive-bg-hover-solid': '#45475a',
      '--dsw-alias-interactive-bg-hover-danger': 'rgba(243, 139, 168, 0.15)',
      '--dsw-alias-label-primary': '#cdd6f4',
      '--dsw-alias-label-secondary': '#a6adc8',
      '--dsw-alias-label-tertiary': '#6c7086',
      '--dsw-alias-label-caption': '#6c7086',
      '--dsw-alias-label-dimmed': '#45475a',
      '--dsw-alias-label-primary-foreground': '#1e1e2e',
      '--dsw-alias-label-primary-inverted': '#1e1e2e',
      '--dsw-alias-label-primary-bluish': '#cdd6f4',
      '--dsw-alias-label-primary-dimmed': '#45475a',
      '--dsw-alias-markdown-code-block': '#181825',
      '--dsw-alias-markdown-code-block-banner': '#313244',
      '--dsw-alias-markdown-inline-code': '#313244',
      '--dsw-alias-markdown-citation': '#45475a',
      '--dsw-alias-markdown-tag': '#313244',
      '--dsw-alias-markdown-placeholder': '#313244',
      '--dsw-alias-markdown-code-segment-selected': '#313244',
      '--dsw-alias-markdown-code-segment-unselected': '#181825',
      '--dsw-alias-scrollbar-bg-l1': '#45475a',
      '--dsw-alias-scrollbar-bg-l2': '#585b70',
      '--dsw-alias-scrollbar-hover-l1': '#585b70',
      '--dsw-alias-scrollbar-hover-l2': '#6c7086',
      '--dsw-alias-state-business-primary': '#89b4fa',
      '--dsw-alias-state-business-tertiary': '#313244',
      '--dsw-alias-toast-bg': '#45475a',
      '--dsw-alias-tooltip-bg': '#45475a',
      '--dsw-specific-bubble': '#181825',
      '--dsw-specific-bubble-highlight': '#313244',
      '--dsw-specific-input-major': '#181825',
      '--dsw-specific-login-input': '#1e1e2e',
      '--dsw-specific-selector': '#313244',
      '--dsw-specific-sidebar-fill': '#1e1e2e',
      '--dsw-specific-sidebar-nav-item-active': '#313244',
      '--dsw-specific-sidebar-nav-item-active-accent': '#45475a',
      '--dsw-specific-sidebar-nav-item-hover': '#26263a',
      '--dsw-specific-tip': '#313244',
    },
  },
  {
    id: 'everforest',
    colorScheme: 'dark',
    labelKey: 'palette.everforest',
    swatchAccent: '#a7c080',
    swatchBackground: '#2d353b',
    tokens: {
      '--dsw-alias-bg-base': '#2d353b',
      '--dsw-alias-bg-layer-1': '#2d353b',
      '--dsw-alias-bg-layer-2': '#333c43',
      '--dsw-alias-bg-layer-3': '#3a454d',
      '--dsw-alias-bg-overlay': '#465258',
      '--dsw-alias-bg-module-platform': '#333c43',
      '--dsw-alias-bg-multi-select': '#2d353b',
      '--dsw-alias-bg-skeleton': 'rgba(211, 198, 170, 0.08)',
      '--dsw-alias-bg-mask-drop': 'rgba(45, 53, 59, 0.72)',
      '--dsw-alias-border-l1': 'rgba(211, 198, 170, 0.09)',
      '--dsw-alias-border-l2': 'rgba(211, 198, 170, 0.15)',
      '--dsw-alias-border-l2-darkmode-thin': 'rgba(211, 198, 170, 0.09)',
      '--dsw-alias-border-l3': 'rgba(211, 198, 170, 0.22)',
      '--dsw-alias-border-l4': 'rgba(211, 198, 170, 0.3)',
      '--dsw-alias-border-inverted': 'rgba(0, 0, 0, 0.2)',
      '--dsw-alias-border-inverted2': 'rgba(0, 0, 0, 0.34)',
      '--dsw-alias-brand-primary': '#a7c080',
      '--dsw-alias-brand-primary-invert': '#2d353b',
      '--dsw-alias-brand-primary-new-colorprimary-new-color': '#a7c080',
      '--dsw-alias-brand-text': '#d3c6aa',
      '--dsw-alias-button-primary-fill': '#a7c080',
      '--dsw-alias-button-primary-hover': '#b5cc92',
      '--dsw-alias-button-primary-dimmed': '#333c43',
      '--dsw-alias-button-info-fill': '#7fbbb3',
      '--dsw-alias-button-info-hover': '#92c5bf',
      '--dsw-alias-button-contrast-fill': '#d3c6aa',
      '--dsw-alias-button-elevated-fill': '#333c43',
      '--dsw-alias-button-floating-fill': '#3a454d',
      '--dsw-alias-button-floating-hover': '#465258',
      '--dsw-alias-button-ghost-active-border': '#859289',
      '--dsw-alias-button-ghost-active-fill': '#333c43',
      '--dsw-alias-button-ghost-active-hover': '#3a454d',
      '--dsw-alias-interactive-bg-hover': 'rgba(211, 198, 170, 0.07)',
      '--dsw-alias-interactive-bg-active': 'rgba(211, 198, 170, 0.12)',
      '--dsw-alias-interactive-bg-hover-accent': 'rgba(167, 192, 128, 0.16)',
      '--dsw-alias-interactive-bg-hover-solid': '#3a454d',
      '--dsw-alias-interactive-bg-hover-danger': 'rgba(230, 126, 128, 0.15)',
      '--dsw-alias-label-primary': '#d3c6aa',
      '--dsw-alias-label-secondary': '#a5b0a5',
      '--dsw-alias-label-tertiary': '#859289',
      '--dsw-alias-label-caption': '#859289',
      '--dsw-alias-label-dimmed': '#465258',
      '--dsw-alias-label-primary-foreground': '#2d353b',
      '--dsw-alias-label-primary-inverted': '#2d353b',
      '--dsw-alias-label-primary-bluish': '#d3c6aa',
      '--dsw-alias-label-primary-dimmed': '#465258',
      '--dsw-alias-markdown-code-block': '#333c43',
      '--dsw-alias-markdown-code-block-banner': '#333c43',
      '--dsw-alias-markdown-inline-code': '#333c43',
      '--dsw-alias-markdown-citation': '#3a454d',
      '--dsw-alias-markdown-tag': '#333c43',
      '--dsw-alias-markdown-placeholder': '#3a454d',
      '--dsw-alias-markdown-code-segment-selected': '#3a454d',
      '--dsw-alias-markdown-code-segment-unselected': '#2d353b',
      '--dsw-alias-scrollbar-bg-l1': '#3a454d',
      '--dsw-alias-scrollbar-bg-l2': '#465258',
      '--dsw-alias-scrollbar-hover-l1': '#465258',
      '--dsw-alias-scrollbar-hover-l2': '#525f66',
      '--dsw-alias-state-business-primary': '#a7c080',
      '--dsw-alias-state-business-tertiary': '#333c43',
      '--dsw-alias-toast-bg': '#465258',
      '--dsw-alias-tooltip-bg': '#465258',
      '--dsw-specific-bubble': '#333c43',
      '--dsw-specific-bubble-highlight': '#3a454d',
      '--dsw-specific-input-major': '#333c43',
      '--dsw-specific-login-input': '#2d353b',
      '--dsw-specific-selector': '#333c43',
      '--dsw-specific-sidebar-fill': '#293137',
      '--dsw-specific-sidebar-nav-item-active': '#333c43',
      '--dsw-specific-sidebar-nav-item-active-accent': '#3a454d',
      '--dsw-specific-sidebar-nav-item-hover': '#303b42',
      '--dsw-specific-tip': '#333c43',
    },
  },
  {
    id: 'rose-pine',
    colorScheme: 'dark',
    labelKey: 'palette.rosePine',
    swatchAccent: '#ebbcba',
    swatchBackground: '#191724',
    tokens: {
      '--dsw-alias-bg-base': '#191724',
      '--dsw-alias-bg-layer-1': '#191724',
      '--dsw-alias-bg-layer-2': '#1f1d2e',
      '--dsw-alias-bg-layer-3': '#26233a',
      '--dsw-alias-bg-overlay': '#403d52',
      '--dsw-alias-bg-module-platform': '#1f1d2e',
      '--dsw-alias-bg-multi-select': '#191724',
      '--dsw-alias-bg-skeleton': 'rgba(224, 222, 244, 0.08)',
      '--dsw-alias-bg-mask-drop': 'rgba(25, 23, 36, 0.72)',
      '--dsw-alias-border-l1': 'rgba(224, 222, 244, 0.08)',
      '--dsw-alias-border-l2': 'rgba(224, 222, 244, 0.14)',
      '--dsw-alias-border-l2-darkmode-thin': 'rgba(224, 222, 244, 0.08)',
      '--dsw-alias-border-l3': 'rgba(224, 222, 244, 0.2)',
      '--dsw-alias-border-l4': 'rgba(224, 222, 244, 0.28)',
      '--dsw-alias-border-inverted': 'rgba(0, 0, 0, 0.2)',
      '--dsw-alias-border-inverted2': 'rgba(0, 0, 0, 0.34)',
      '--dsw-alias-brand-primary': '#ebbcba',
      '--dsw-alias-brand-primary-invert': '#191724',
      '--dsw-alias-brand-primary-new-colorprimary-new-color': '#ebbcba',
      '--dsw-alias-brand-text': '#e0def4',
      '--dsw-alias-button-primary-fill': '#ebbcba',
      '--dsw-alias-button-primary-hover': '#f0cfcd',
      '--dsw-alias-button-primary-dimmed': '#1f1d2e',
      '--dsw-alias-button-info-fill': '#c4a7e7',
      '--dsw-alias-button-info-hover': '#cfb5ed',
      '--dsw-alias-button-contrast-fill': '#e0def4',
      '--dsw-alias-button-elevated-fill': '#1f1d2e',
      '--dsw-alias-button-floating-fill': '#26233a',
      '--dsw-alias-button-floating-hover': '#403d52',
      '--dsw-alias-button-ghost-active-border': '#6e6a86',
      '--dsw-alias-button-ghost-active-fill': '#1f1d2e',
      '--dsw-alias-button-ghost-active-hover': '#26233a',
      '--dsw-alias-interactive-bg-hover': 'rgba(224, 222, 244, 0.07)',
      '--dsw-alias-interactive-bg-active': 'rgba(224, 222, 244, 0.12)',
      '--dsw-alias-interactive-bg-hover-accent': 'rgba(235, 188, 186, 0.16)',
      '--dsw-alias-interactive-bg-hover-solid': '#26233a',
      '--dsw-alias-interactive-bg-hover-danger': 'rgba(235, 111, 146, 0.15)',
      '--dsw-alias-label-primary': '#e0def4',
      '--dsw-alias-label-secondary': '#908caa',
      '--dsw-alias-label-tertiary': '#6e6a86',
      '--dsw-alias-label-caption': '#6e6a86',
      '--dsw-alias-label-dimmed': '#403d52',
      '--dsw-alias-label-primary-foreground': '#191724',
      '--dsw-alias-label-primary-inverted': '#191724',
      '--dsw-alias-label-primary-bluish': '#e0def4',
      '--dsw-alias-label-primary-dimmed': '#403d52',
      '--dsw-alias-markdown-code-block': '#1f1d2e',
      '--dsw-alias-markdown-code-block-banner': '#1f1d2e',
      '--dsw-alias-markdown-inline-code': '#1f1d2e',
      '--dsw-alias-markdown-citation': '#26233a',
      '--dsw-alias-markdown-tag': '#1f1d2e',
      '--dsw-alias-markdown-placeholder': '#26233a',
      '--dsw-alias-markdown-code-segment-selected': '#26233a',
      '--dsw-alias-markdown-code-segment-unselected': '#191724',
      '--dsw-alias-scrollbar-bg-l1': '#26233a',
      '--dsw-alias-scrollbar-bg-l2': '#403d52',
      '--dsw-alias-scrollbar-hover-l1': '#403d52',
      '--dsw-alias-scrollbar-hover-l2': '#555169',
      '--dsw-alias-state-business-primary': '#f6c177',
      '--dsw-alias-state-business-tertiary': '#1f1d2e',
      '--dsw-alias-toast-bg': '#403d52',
      '--dsw-alias-tooltip-bg': '#403d52',
      '--dsw-specific-bubble': '#1f1d2e',
      '--dsw-specific-bubble-highlight': '#26233a',
      '--dsw-specific-input-major': '#1f1d2e',
      '--dsw-specific-login-input': '#191724',
      '--dsw-specific-selector': '#1f1d2e',
      '--dsw-specific-sidebar-fill': '#191724',
      '--dsw-specific-sidebar-nav-item-active': '#1f1d2e',
      '--dsw-specific-sidebar-nav-item-active-accent': '#26233a',
      '--dsw-specific-sidebar-nav-item-hover': '#1c1a29',
      '--dsw-specific-tip': '#1f1d2e',
    },
  },
  {
    id: 'ayu-mirage',
    colorScheme: 'dark',
    labelKey: 'palette.ayuMirage',
    swatchAccent: '#ffcc66',
    swatchBackground: '#1f2430',
    tokens: {
      '--dsw-alias-bg-base': '#1f2430',
      '--dsw-alias-bg-layer-1': '#1f2430',
      '--dsw-alias-bg-layer-2': '#171b24',
      '--dsw-alias-bg-layer-3': '#242936',
      '--dsw-alias-bg-overlay': '#2a3040',
      '--dsw-alias-bg-module-platform': '#242936',
      '--dsw-alias-bg-multi-select': '#171b24',
      '--dsw-alias-bg-skeleton': 'rgba(203, 204, 198, 0.08)',
      '--dsw-alias-bg-mask-drop': 'rgba(31, 36, 48, 0.72)',
      '--dsw-alias-border-l1': 'rgba(203, 204, 198, 0.08)',
      '--dsw-alias-border-l2': 'rgba(203, 204, 198, 0.14)',
      '--dsw-alias-border-l2-darkmode-thin': 'rgba(203, 204, 198, 0.08)',
      '--dsw-alias-border-l3': 'rgba(203, 204, 198, 0.2)',
      '--dsw-alias-border-l4': 'rgba(203, 204, 198, 0.28)',
      '--dsw-alias-border-inverted': 'rgba(0, 0, 0, 0.2)',
      '--dsw-alias-border-inverted2': 'rgba(0, 0, 0, 0.34)',
      '--dsw-alias-brand-primary': '#ffcc66',
      '--dsw-alias-brand-primary-invert': '#1f2430',
      '--dsw-alias-brand-primary-new-colorprimary-new-color': '#ffcc66',
      '--dsw-alias-brand-text': '#cbccc6',
      '--dsw-alias-button-primary-fill': '#ffcc66',
      '--dsw-alias-button-primary-hover': '#ffd580',
      '--dsw-alias-button-primary-dimmed': '#242936',
      '--dsw-alias-button-info-fill': '#39bae6',
      '--dsw-alias-button-info-hover': '#5ccfe6',
      '--dsw-alias-button-contrast-fill': '#cbccc6',
      '--dsw-alias-button-elevated-fill': '#242936',
      '--dsw-alias-button-floating-fill': '#2a3040',
      '--dsw-alias-button-floating-hover': '#343c4f',
      '--dsw-alias-button-ghost-active-border': '#6c7380',
      '--dsw-alias-button-ghost-active-fill': '#242936',
      '--dsw-alias-button-ghost-active-hover': '#2a3040',
      '--dsw-alias-interactive-bg-hover': 'rgba(203, 204, 198, 0.07)',
      '--dsw-alias-interactive-bg-active': 'rgba(203, 204, 198, 0.12)',
      '--dsw-alias-interactive-bg-hover-accent': 'rgba(255, 204, 102, 0.16)',
      '--dsw-alias-interactive-bg-hover-solid': '#2a3040',
      '--dsw-alias-interactive-bg-hover-danger': 'rgba(255, 102, 102, 0.15)',
      '--dsw-alias-label-primary': '#cbccc6',
      '--dsw-alias-label-secondary': '#9aa2ad',
      '--dsw-alias-label-tertiary': '#6c7380',
      '--dsw-alias-label-caption': '#6c7380',
      '--dsw-alias-label-dimmed': '#2a3040',
      '--dsw-alias-label-primary-foreground': '#171b24',
      '--dsw-alias-label-primary-inverted': '#171b24',
      '--dsw-alias-label-primary-bluish': '#cbccc6',
      '--dsw-alias-label-primary-dimmed': '#2a3040',
      '--dsw-alias-markdown-code-block': '#171b24',
      '--dsw-alias-markdown-code-block-banner': '#242936',
      '--dsw-alias-markdown-inline-code': '#242936',
      '--dsw-alias-markdown-citation': '#2a3040',
      '--dsw-alias-markdown-tag': '#242936',
      '--dsw-alias-markdown-placeholder': '#242936',
      '--dsw-alias-markdown-code-segment-selected': '#242936',
      '--dsw-alias-markdown-code-segment-unselected': '#171b24',
      '--dsw-alias-scrollbar-bg-l1': '#2a3040',
      '--dsw-alias-scrollbar-bg-l2': '#343c4f',
      '--dsw-alias-scrollbar-hover-l1': '#343c4f',
      '--dsw-alias-scrollbar-hover-l2': '#414a61',
      '--dsw-alias-state-business-primary': '#ffcc66',
      '--dsw-alias-state-business-tertiary': '#242936',
      '--dsw-alias-toast-bg': '#2a3040',
      '--dsw-alias-tooltip-bg': '#2a3040',
      '--dsw-specific-bubble': '#171b24',
      '--dsw-specific-bubble-highlight': '#242936',
      '--dsw-specific-input-major': '#171b24',
      '--dsw-specific-login-input': '#1f2430',
      '--dsw-specific-selector': '#242936',
      '--dsw-specific-sidebar-fill': '#1b202b',
      '--dsw-specific-sidebar-nav-item-active': '#242936',
      '--dsw-specific-sidebar-nav-item-active-accent': '#2a3040',
      '--dsw-specific-sidebar-nav-item-hover': '#1f2531',
      '--dsw-specific-tip': '#242936',
    },
  },
  {
    id: 'catppuccin-latte',
    colorScheme: 'light',
    labelKey: 'palette.catppuccinLatte',
    swatchAccent: '#8839ef',
    swatchBackground: '#eff1f5',
    tokens: {
      '--dsw-alias-bg-base': '#eff1f5',
      '--dsw-alias-bg-layer-1': '#eff1f5',
      '--dsw-alias-bg-layer-2': '#e6e9ef',
      '--dsw-alias-bg-layer-3': '#ccd0da',
      '--dsw-alias-bg-overlay': '#e6e9ef',
      '--dsw-alias-bg-module-platform': '#e6e9ef',
      '--dsw-alias-bg-multi-select': '#e6e9ef',
      '--dsw-alias-bg-skeleton': 'rgba(76, 79, 105, 0.05)',
      '--dsw-alias-bg-mask-drop': 'rgba(239, 241, 245, 0.72)',
      '--dsw-alias-border-l1': 'rgba(76, 79, 105, 0.08)',
      '--dsw-alias-border-l2': 'rgba(76, 79, 105, 0.14)',
      '--dsw-alias-border-l2-darkmode-thin': 'rgba(76, 79, 105, 0.08)',
      '--dsw-alias-border-l3': 'rgba(76, 79, 105, 0.2)',
      '--dsw-alias-border-l4': 'rgba(76, 79, 105, 0.28)',
      '--dsw-alias-border-inverted': 'rgba(255, 255, 255, 0.4)',
      '--dsw-alias-border-inverted2': 'rgba(255, 255, 255, 0.6)',
      '--dsw-alias-brand-primary': '#8839ef',
      '--dsw-alias-brand-primary-invert': '#eff1f5',
      '--dsw-alias-brand-primary-new-colorprimary-new-color': '#8839ef',
      '--dsw-alias-brand-text': '#4c4f69',
      '--dsw-alias-button-primary-fill': '#8839ef',
      '--dsw-alias-button-primary-hover': '#9a55f1',
      '--dsw-alias-button-primary-dimmed': '#e6e9ef',
      '--dsw-alias-button-info-fill': '#1e66f5',
      '--dsw-alias-button-info-hover': '#4a82f7',
      '--dsw-alias-button-contrast-fill': '#4c4f69',
      '--dsw-alias-button-elevated-fill': '#ffffff',
      '--dsw-alias-button-floating-fill': '#ffffff',
      '--dsw-alias-button-floating-hover': '#e6e9ef',
      '--dsw-alias-button-ghost-active-border': '#9ca0b0',
      '--dsw-alias-button-ghost-active-fill': '#e6e9ef',
      '--dsw-alias-button-ghost-active-hover': '#ccd0da',
      '--dsw-alias-interactive-bg-hover': 'rgba(76, 79, 105, 0.06)',
      '--dsw-alias-interactive-bg-active': 'rgba(76, 79, 105, 0.1)',
      '--dsw-alias-interactive-bg-hover-accent': 'rgba(136, 57, 239, 0.1)',
      '--dsw-alias-interactive-bg-hover-solid': '#e6e9ef',
      '--dsw-alias-interactive-bg-hover-danger': 'rgba(210, 15, 57, 0.05)',
      '--dsw-alias-label-primary': '#4c4f69',
      '--dsw-alias-label-secondary': '#6c6f85',
      '--dsw-alias-label-tertiary': '#9ca0b0',
      '--dsw-alias-label-caption': '#9ca0b0',
      '--dsw-alias-label-dimmed': '#ccd0da',
      '--dsw-alias-label-primary-foreground': '#eff1f5',
      '--dsw-alias-label-primary-inverted': '#ffffff',
      '--dsw-alias-label-primary-bluish': '#1e66f5',
      '--dsw-alias-label-primary-dimmed': '#ccd0da',
      '--dsw-alias-markdown-code-block': '#e6e9ef',
      '--dsw-alias-markdown-code-block-banner': '#e6e9ef',
      '--dsw-alias-markdown-inline-code': '#e6e9ef',
      '--dsw-alias-markdown-citation': '#ccd0da',
      '--dsw-alias-markdown-tag': '#e6e9ef',
      '--dsw-alias-markdown-placeholder': '#e6e9ef',
      '--dsw-alias-markdown-code-segment-selected': '#ffffff',
      '--dsw-alias-markdown-code-segment-unselected': '#e6e9ef',
      '--dsw-alias-scrollbar-bg-l1': '#ccd0da',
      '--dsw-alias-scrollbar-bg-l2': '#bcc0cc',
      '--dsw-alias-scrollbar-hover-l1': '#bcc0cc',
      '--dsw-alias-scrollbar-hover-l2': '#acb0be',
      '--dsw-alias-state-business-primary': '#8839ef',
      '--dsw-alias-state-business-tertiary': '#e6e9ef',
      '--dsw-alias-toast-bg': '#4c4f69',
      '--dsw-alias-tooltip-bg': '#4c4f69',
      '--dsw-specific-bubble': '#e6e9ef',
      '--dsw-specific-bubble-highlight': '#ccd0da',
      '--dsw-specific-input-major': '#eff1f5',
      '--dsw-specific-login-input': '#e6e9ef',
      '--dsw-specific-selector': '#e6e9ef',
      '--dsw-specific-sidebar-fill': '#e6e9ef',
      '--dsw-specific-sidebar-nav-item-active': '#ccd0da',
      '--dsw-specific-sidebar-nav-item-active-accent': '#d6dae3',
      '--dsw-specific-sidebar-nav-item-hover': '#e0e3ea',
      '--dsw-specific-tip': '#e6e9ef',
    },
  },
  {
    id: 'paper-gold',
    colorScheme: 'light',
    labelKey: 'palette.paperGold',
    swatchAccent: '#9c7a3c',
    swatchBackground: '#f6f3ec',
    tokens: {
      '--dsw-alias-bg-base': '#f6f3ec',
      '--dsw-alias-bg-layer-1': '#f6f3ec',
      '--dsw-alias-bg-layer-2': '#efeae0',
      '--dsw-alias-bg-layer-3': '#e6dfd1',
      '--dsw-alias-bg-overlay': '#efeae0',
      '--dsw-alias-bg-module-platform': '#efeae0',
      '--dsw-alias-bg-multi-select': '#efeae0',
      '--dsw-alias-bg-skeleton': 'rgba(35, 32, 26, 0.05)',
      '--dsw-alias-bg-mask-drop': 'rgba(246, 243, 236, 0.72)',
      '--dsw-alias-border-l1': 'rgba(35, 32, 26, 0.08)',
      '--dsw-alias-border-l2': 'rgba(35, 32, 26, 0.16)',
      '--dsw-alias-border-l2-darkmode-thin': 'rgba(35, 32, 26, 0.08)',
      '--dsw-alias-border-l3': 'rgba(35, 32, 26, 0.24)',
      '--dsw-alias-border-l4': 'rgba(35, 32, 26, 0.34)',
      '--dsw-alias-border-inverted': 'rgba(255, 255, 255, 0.45)',
      '--dsw-alias-border-inverted2': 'rgba(255, 255, 255, 0.65)',
      '--dsw-alias-brand-primary': '#9c7a3c',
      '--dsw-alias-brand-primary-invert': '#f6f3ec',
      '--dsw-alias-brand-primary-new-colorprimary-new-color': '#9c7a3c',
      '--dsw-alias-brand-text': '#23201a',
      '--dsw-alias-button-primary-fill': '#9c7a3c',
      '--dsw-alias-button-primary-hover': '#ab8a4a',
      '--dsw-alias-button-primary-dimmed': '#efeae0',
      '--dsw-alias-button-info-fill': '#9c7a3c',
      '--dsw-alias-button-info-hover': '#ab8a4a',
      '--dsw-alias-button-contrast-fill': '#23201a',
      '--dsw-alias-button-elevated-fill': '#fdfbf7',
      '--dsw-alias-button-floating-fill': '#fdfbf7',
      '--dsw-alias-button-floating-hover': '#efeae0',
      '--dsw-alias-button-ghost-active-border': '#8a8275',
      '--dsw-alias-button-ghost-active-fill': '#efeae0',
      '--dsw-alias-button-ghost-active-hover': '#e6dfd1',
      '--dsw-alias-interactive-bg-hover': 'rgba(35, 32, 26, 0.05)',
      '--dsw-alias-interactive-bg-active': 'rgba(35, 32, 26, 0.09)',
      '--dsw-alias-interactive-bg-hover-accent': 'rgba(156, 122, 60, 0.12)',
      '--dsw-alias-interactive-bg-hover-solid': '#efeae0',
      '--dsw-alias-interactive-bg-hover-danger': 'rgba(236, 19, 19, 0.05)',
      '--dsw-alias-label-primary': '#23201a',
      '--dsw-alias-label-secondary': '#5c554a',
      '--dsw-alias-label-tertiary': '#8a8275',
      '--dsw-alias-label-caption': '#8a8275',
      '--dsw-alias-label-dimmed': '#e6dfd1',
      '--dsw-alias-label-primary-foreground': '#f6f3ec',
      '--dsw-alias-label-primary-inverted': '#fdfbf7',
      '--dsw-alias-label-primary-bluish': '#9c7a3c',
      '--dsw-alias-label-primary-dimmed': '#e6dfd1',
      '--dsw-alias-markdown-code-block': '#efeae0',
      '--dsw-alias-markdown-code-block-banner': '#efeae0',
      '--dsw-alias-markdown-inline-code': '#efeae0',
      '--dsw-alias-markdown-citation': '#e6dfd1',
      '--dsw-alias-markdown-tag': '#efeae0',
      '--dsw-alias-markdown-placeholder': '#efeae0',
      '--dsw-alias-markdown-code-segment-selected': '#fdfbf7',
      '--dsw-alias-markdown-code-segment-unselected': '#efeae0',
      '--dsw-alias-scrollbar-bg-l1': '#e6dfd1',
      '--dsw-alias-scrollbar-bg-l2': '#d8cfbd',
      '--dsw-alias-scrollbar-hover-l1': '#d8cfbd',
      '--dsw-alias-scrollbar-hover-l2': '#c9bea8',
      '--dsw-alias-state-business-primary': '#9c7a3c',
      '--dsw-alias-state-business-tertiary': '#efeae0',
      '--dsw-alias-toast-bg': '#2c281f',
      '--dsw-alias-tooltip-bg': '#2c281f',
      '--dsw-specific-bubble': '#efeae0',
      '--dsw-specific-bubble-highlight': '#e6dfd1',
      '--dsw-specific-input-major': '#fdfbf7',
      '--dsw-specific-login-input': '#f6f3ec',
      '--dsw-specific-selector': '#efeae0',
      '--dsw-specific-sidebar-fill': '#efeae0',
      '--dsw-specific-sidebar-nav-item-active': '#e6dfd1',
      '--dsw-specific-sidebar-nav-item-active-accent': '#dcd3c2',
      '--dsw-specific-sidebar-nav-item-hover': '#eae3d6',
      '--dsw-specific-tip': '#efeae0',
    },
  },
]
